#!/usr/bin/env python3
"""
Run every reproduction/checks/check_volume*.py script, capture its pass/fail/tier status,
and write LEDGER.json (machine-readable) and LEDGER.md (human-readable table).

Volumes 1-6 are the deposited development series. Volume 7 is the later EPSC
research lane and is clearly marked as post-paper in the repository claim boundary.

This ledger is REGENERATED by running this script -- it is never hand-typed. Run it via
`bash reproduce_all.sh` or directly: `python3 generate_ledger.py`.
"""
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CHECKS_DIR = HERE / "checks"

TIER_LABEL = {
    "Th_coqc": "Th_coqc (Coq machine-checked)",
    "finite_diagnostic": "finite_diagnostic (script-verified)",
    "Dr": "Dr (standard analysis, not mechanically checkable)",
    "Open": "Open (unresolved / explicitly posed)",
    "N/A": "N/A",
}


def run_check(script_path):
    proc = subprocess.run(
        [sys.executable, str(script_path)],
        capture_output=True, text=True, timeout=300,
    )
    stdout = proc.stdout
    claims = []
    result_json_line = None
    for line in stdout.splitlines():
        if line.startswith("RESULT_JSON:"):
            result_json_line = line[len("RESULT_JSON:"):]
    if result_json_line:
        try:
            parsed = json.loads(result_json_line)
            claims = parsed.get("claims", [])
        except json.JSONDecodeError as e:
            claims = []
            print(f"WARNING: could not parse RESULT_JSON from {script_path.name}: {e}", file=sys.stderr)
    return {
        "script": script_path.name,
        "returncode": proc.returncode,
        "stdout": stdout,
        "stderr": proc.stderr,
        "claims": claims,
    }


def volume_from_script_name(name: str) -> int:
    """Read only the canonical volume prefix; ignore digits in suffixes such as rk4."""
    match = re.match(r"^check_volume(\d+)(?:_|\.py$)", name)
    if not match:
        raise ValueError(f"cannot parse volume from check script name: {name}")
    return int(match.group(1))


def main():
    scripts = sorted(CHECKS_DIR.glob("check_volume*.py"))
    if not scripts:
        print("No check scripts found in", CHECKS_DIR, file=sys.stderr)
        return 1

    run_results = []
    all_claims = []
    any_unexpected_failure = False

    for script in scripts:
        print(f"--- running {script.name} ---")
        result = run_check(script)
        print(result["stdout"])
        if result["stderr"].strip():
            print("[stderr]", result["stderr"], file=sys.stderr)
        run_results.append(result)
        for c in result["claims"]:
            all_claims.append(c)
        if result["returncode"] != 0:
            any_unexpected_failure = True

    rows = []
    for result in run_results:
        vol_num = volume_from_script_name(result["script"])
        for c in result["claims"]:
            rows.append({
                "volume": vol_num,
                "id": c.get("id", ""),
                "name": c.get("name", ""),
                "tier": c.get("tier", ""),
                "status": c.get("status", ""),
                "evidence": c.get("evidence", ""),
            })

    counts = {}
    for r in rows:
        counts[r["tier"]] = counts.get(r["tier"], 0) + 1
    status_counts = {}
    for r in rows:
        status_counts[r["status"]] = status_counts.get(r["status"], 0) + 1

    ledger = {
        "generated_at_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "series": "Readout-Navier-Stokes Development Series (Volumes 1-6) + post-paper EPSC research lane (Volume 7)",
        "source_repos": [
            "GLS-2026-006 (github.com/morrocwi/readout-problem-navier-stokes, Zenodo DOI 10.5281/zenodo.22673246)",
            "GLS-2026-007 (glosa project, Volumes 1-6, 49-page combined PDF, P02 intake)",
            "Post-paper EPSC Volume 7 (this repository; not part of deposited v0.1.0 unless a future release incorporates it)",
        ],
        "total_claims": len(rows),
        "tier_counts": counts,
        "status_counts": status_counts,
        "any_check_script_reported_failure": any_unexpected_failure,
        "claims": rows,
        "raw_run_results": [
            {"script": r["script"], "returncode": r["returncode"]} for r in run_results
        ],
    }

    (HERE / "LEDGER.json").write_text(json.dumps(ledger, indent=2))

    md_lines = [
        "# Reproduction Ledger -- Readout-Navier-Stokes Development Series",
        "",
        f"Generated: {ledger['generated_at_utc']}",
        "",
        "Volumes 1-6 are the deposited series; Volume 7 is the later EPSC research lane.",
        "",
        "This file is auto-generated by `generate_ledger.py`. Do not hand-edit it -- edit the",
        "check scripts under `checks/` and re-run `bash reproduce_all.sh` instead.",
        "",
        f"**Total claims tracked: {ledger['total_claims']}**",
        "",
        "Tier counts: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())),
        "",
        "Status counts: " + ", ".join(f"{k}={v}" for k, v in sorted(status_counts.items())),
        "",
        "## Tier legend",
        "",
        "| Tier | Meaning |",
        "|---|---|",
        "| `Th_coqc` | Machine-checked in Coq (none in this reproduction pass -- no Coq file was compiled here) |",
        "| `finite_diagnostic` | An independent script in this repository ran a finite/numeric/symbolic check and produced concrete evidence (printed above the run) |",
        "| `Dr` | Standard analytic/derived mathematics (classical real/functional analysis, standard PDE theory) that is not mechanically checkable by a finite script; not run, not faked |",
        "| `Open` | Explicitly unresolved, hypothetical, or posed-not-answered by the paper itself |",
        "",
        "## Claims",
        "",
        "| Volume | Claim ID | Name | Tier | Status | Evidence |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        name = r["name"].replace("|", "\\|")
        evidence = r["evidence"].replace("|", "\\|").replace("\n", " ")
        if len(evidence) > 220:
            evidence = evidence[:217] + "..."
        md_lines.append(
            f"| {r['volume']} | {r['id']} | {name} | {r['tier']} | {r['status']} | {evidence} |"
        )

    (HERE / "LEDGER.md").write_text("\n".join(md_lines) + "\n")

    print()
    print(f"Wrote {HERE / 'LEDGER.json'} and {HERE / 'LEDGER.md'}")
    print(f"Total claims: {ledger['total_claims']}  tiers: {counts}  statuses: {status_counts}")

    return 1 if any_unexpected_failure else 0


if __name__ == "__main__":
    sys.exit(main())
